apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

resources:
  - namespace.yaml
  - ../../base
  - ../../optional/ingress          # only if you enabled it
  # - ../../optional/loadbalancer   # optional
  # - ../../optional/networkpolicy  # optional
  # - ../../optional/monitoring     # optional

patchesStrategicMerge:
  - patch-deployment.yaml
