apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: "./k8s/overlays/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
  validation: client
